name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Upload debug
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: apk-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
